#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_cb

:|menu-sw-cb|                :en_gb Class Browser
:|cb-menu-start|             :en_gb Run/Goto Class Browser
:|cb-menu-start-new-cb|      :en_gb Start New Class Browser
:|cb-menu-start-method|      :en_gb Paste Method in CB
:|cb-menu-start-class|       :en_gb Paste Class in CB
:|cb-menu-start-m-c|         :en_gb Clear Method and Class in CB

:|cb-menu|                           :en_gb CB
:|cb-menu-jump|                      :en_gb Jump to Source
:|cb-menu-family-tree|               :en_gb Family Tree
:|cb-menu-fold|                      :en_gb Fold
:|cb-menu-unfold|                    :en_gb Unfold
:|cb-menu-options|                   :en_gb Set Options
:|cb-menu-toggle-topics|             :en_gb Turn All Topics On/Off
:|cb-menu-reset|                     :en_gb Reset All Options
:|cb-menu-toggle-override-flags|     :en_gb Override Flags
:|cb-menu-toggle-override-topics|    :en_gb Override Topics
:|cb-menu-toggle-override-200-limit| :en_gb Override 200 Limit
:|cb-menu-tab|                       :en_gb Hop
:|cb-menu-clear|                     :en_gb Clear
:|cb-menu-clear-m-c|                 :en_gb Clear Method and Class
:|cb-menu-quit|                      :en_gb Hide
:|cb-menu-gis|                       :en_gb Gis Process
:|cb-menu-gis-shell|                 :en_gb Gis Shell Process

:|cb-in|                     :en_gb IN

:|cb-enter-buffer|           :en_gb Enter Class Browser buffer:
:|cb-or-gis-enter-buffer|    :en_gb Enter Class Browser or Gis process buffer:
:|cb-enter-load-file|        :en_gb Method Finder File:
:|cb-enter-yn-load-file|     :en_gb `#1' doesn't seem to be a method_finder file.  Load anyway?
:|cb-loading|                :en_gb Loading the documentation ...
:|cb-inherit-local|          :en_gb Setting inheritance mode to 'local-only'.
:|cb-inherit-object|         :en_gb Setting inheritance mode to 'inherit-from-"object"'.
:|cb-inherit-not-object|     :en_gb Setting inheritance mode to 'inherit-not-"object"'.
:|cb-gis-get-mf-busy|        :en_gb The GIS process in buffer #1 is busy... Please wait for CB to start
:|cb-gis-get-mf-abort|       :en_gb The CB cannot start yet because the GIS process in #1 is busy... Abort CB
:|cb-goto-beginning|         :en_gb Press `C-a' again to go right to the beginning.
:|cb-goto-end|               :en_gb Press `C-e' again to go right to the end.
:|cb-yank-one-line|          :en_gb Only yanked the first line.
:|cb-toggle-flag-on|         :en_gb Turning '#1' flag on.
:|cb-toggle-flag-off|        :en_gb Turning '#1' flag off.
:|cb-fully-unfolded|         :en_gb The methods are now fully unfolded
:|cb-fully-folded|           :en_gb The methods are now fully folded

:|cb-modeline-help-flag|     :en_gb mouse-1, mouse-2: toggle #1 flag
:|cb-modeline-help-buffer|   :en_gb mouse-1, mouse-2: Switch to buffer #1
:|cb-modeline-help-cursor|   :en_gb TAB: switch between class and method name

:|cb-file-is-dir-error|      :en_gb Please give a filename of an mf file
:|cb-file-not-loaded|        :en_gb #1 not loaded
:|cb-getenv-error|           :en_gb There is no value for the environment variable, '#1'
:|cb-cannot-jump-error|      :en_gb cb-goto-method (can't jump): #1
:|cb-no-code-error|          :en_gb There is no source code for '#1.#2'
:|cb-no-file-error|          :en_gb Cannot find file, #1
:|cb-no-in-line-error|       :en_gb Can't find a line like: 'my_method  IN  my_class'
:|cb-not-running-error|      :en_gb The Class Browser, '#1', is not running
:|cb-none-running-error|     :en_gb No Class Browser is running
:|cb-no-current-word-error|  :en_gb No current word to use as a method name
:|cb-mf-version-error|       :en_gb unknown - using call-process on the method_finder failed
:|cb-already-unfolded-error| :en_gb The methods are already fully unfolded
:|cb-already-folded-error|   :en_gb The methods are already fully folded
:|cb-no-current-class-error| :en_gb No current word to use as a class-name
