#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_gis

:|gis-menu|                               :en_gb Gis
:|gis-menu-previous|                      :en_gb Previous Command
:|gis-menu-next|                          :en_gb Next Command
:|gis-menu-previous-match|                :en_gb Previous Matching Command
:|gis-menu-next-match|                    :en_gb Next Matching Command

:|gis-menu-fold|                          :en_gb Fold
:|gis-menu-unfold|                        :en_gb Unfold

:|gis-menu-magik-template|                :en_gb Electric Template
:|gis-menu-complete|                      :en_gb Symbol Complete

:|gis-menu-tb-previous|                   :en_gb Previous Traceback
:|gis-menu-tb-next|                       :en_gb Next Traceback
:|gis-menu-tb-print|                      :en_gb Print Traceback
:|gis-menu-tb-save|                       :en_gb Save Traceback

:|gis-menu-shell|                         :en_gb Gis Shell Process
:|gis-menu-kill|                          :en_gb Kill Gis Process
:|gis-menu-history|                       :en_gb Gis Command History
:|gis-menu-no-history|                    :en_gb No History

:|gis-menu-toggle|                        :en_gb Toggle...
:|gis-menu-toggle-filter|                 :en_gb GIS Process Filter
:|gis-menu-toggle-drag-n-drop|            :en_gb Drag and Drop

:|gis-command-prompt|                     :en_gb Gis command:
:|gis-enter-buffer|                       :en_gb Enter Gis process buffer:

:|gis-resizing-vector|                    :en_gb Re-sizing the command history vector...
:|gis-resizing-vector-done|               :en_gb Re-sizing the command history vector...Done. (#1 commands).
:|gis-not-sent-waiting-for|               :en_gb Not sent (waiting for '#1').
:|gis-not-send-pending-op|                :en_gb Not sent (there is a pending operator '#1').
:|gis-folding-commands|                   :en_gb Folding the last #1 commands...
:|gis-folding-commands-done|              :en_gb Folding the last #1 commands...Done
:|gis-unfolding-commands|                 :en_gb Unfolding the last #1 commands...
:|gis-unfolding-commands-done|            :en_gb Unfolding the last #1 commands...Done
:|gis-printing|                           :en_gb Printing...
:|gis-printing-done|                      :en_gb Printing...Done
:|gis-save-traceback|                     :en_gb Saved the traceback in '#1'.
:|gis-kill-process-pending|               :en_gb Magik is still busy and will exit at an appropriate point. Please be patient...
:|gis-sentinel-process-text|              :en_gb Process #1 #2
:|gis-sentinel-process-exited|            :en_gb GIS #1 exited: #2
:|gis-sentinel-process-signalled|         :en_gb GIS #1 signalled: #2
:|gis-sentinel-process-terminated|        :en_gb GIS #1 process #2 has terminated with exit code: #3
:|gis-drag-n-drop-on|                     :en_gb GIS Drag 'n' Drop file mode is on
:|gis-drag-n-drop-off|                    :en_gb GIS Drag 'n' Drop file mode is off
:|gis-filtering-magik|                    :en_gb Filtering Magik output...(#1 chars)
:|gis-filter-set|                         :en_gb Set the filter in '#1'.
:|gis-filter-cancelled|                   :en_gb Cancelled the filter in '#1'.
:|gis-filter-char-set|                    :en_gb Filter action for '#1' is already set
:|gis-filter-complete-no-match|           :en_gb Cannot find completion for #1.
:|gis-filter-complete-sole|               :en_gb Sole completion.
:|gis-filter-complete-done|               :en_gb Finding completions...Done.

:|gis-yn-kill-gis|                        :en_gb Kill the Gis?
:|gis-yn-suspend-gis|                     :en_gb Suspend the Gis?
:|gis-yn-eof-gis|                         :en_gb Send EOF to the Gis?
:|gis-yn-kill-region|                     :en_gb Cutting and pasting big regions can confuse the gis-mode markers. Kill anyway?
:|gis-yn-print-last-traceback|            :en_gb Print the last traceback (#1 lines)?

:|gis-scan-error|                         :en_gb #1 or quotes
:|gis-long-line-error|                    :en_gb Sending long lines will probably crash the gis buffer. Use load_file instead.
:|gis-no-end-token-error|                 :en_gb Found '#1' with no corresponding '#2'
:|gis-expecting-token-error|              :en_gb Found '#1' when expecting '#2'
:|gis-command-recall-error|               :en_gb Sorry... Confused command recall
:|gis-no-process-error|                   :en_gb There is no process running in this buffer
:|gis-not-command-error|                  :en_gb Not a command
:|gis-no-previous-command-error|          :en_gb No previous command
:|gis-no-previous-matching-command-error| :en_gb No previous command matching '#1'
:|gis-no-commands-to-fold|                :en_gb No commands to fold
:|gis-no-commands-to-unfold|              :en_gb No commands to unfold
:|gis-no-error-line-print-error|          :en_gb Couldn't find a line starting with '#1' - nothing printed
:|gis-no-error-line-save-error|           :en_gb Couldn't find a line starting with '#1' - nothing saved
:|gis-filter-char-error|                  :en_gb No filter defined for character #1
:|gis-goto-error-invalid-line|            :en_gb No Error on this line to go to

:|auto-gis-load-file|                     :en_gb Gis process buffer #1 : Loading file #2
:|auto-gis-no-command-error|              :en_gb No Gis command given on command line
