#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_loadlist

:|loadlist-menu|                :en_gb Loadlist
:|loadlist-menu-refresh|        :en_gb Refresh Buffer from Directory
:|loadlist-menu-transmit|       :en_gb Transmit Buffer
:|loadlist-menu-toggle-compile| :en_gb Toggle: Save Compiled Files

:|loadlist-compile-files-on|    :en_gb Will compile files when loading.
:|loadlist-compile-files-off|   :en_gb Will not (re)compile files when loading.

:|loadlist-loaded-in-buffer|    :en_gb #1 loaded in buffer #2.
:|loadlist-output-updated|      :en_gb Updated '#1' with '#2'
:|loadlist-output-append|       :en_gb Append '#1'
:|loadlist-output-ignored|      :en_gb Ignored '#1'
:|loadlist-output-remove|       :en_gb Remove '#1'
:|loadlist-output-no-changes|   :en_gb No changes required in buffer
