#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_magik

:|magik-menu|                          :en_gb Magik
:|magik-menu-transmit-method|          :en_gb Transmit Method
:|magik-menu-transmit-region|          :en_gb Transmit Region
:|magik-menu-transmit-buffer|          :en_gb Transmit Buffer
:|magik-menu-transmit-chunk|           :en_gb Transmit $ Chunk
:|magik-menu-transmit-thing|           :en_gb Transmit Thing

:|magik-menu-work-copy-method|         :en_gb Copy Method to Work Buffer
:|magik-menu-work-copy-region|         :en_gb Copy Region to Work Buffer
:|magik-menu-work-set-buffer|          :en_gb Set Work Buffer Name

:|magik-menu-electric-template|        :en_gb Electric Template
:|magik-menu-mark-method|              :en_gb Mark Method
:|magik-menu-copy-method|              :en_gb Copy Method
:|magik-menu-compare-methods|          :en_gb Compare Method between Windows
:|magik-menu-ediff-methods|            :en_gb Compare Method using Ediff
:|magik-menu-cb-ediff-methods|	       :en_gb Compare Method using CB and Ediff

:|magik-menu-add-debug|                :en_gb Add Debug Statement
:|magik-menu-trace|                    :en_gb Trace Statement
:|magik-menu-complete|                 :en_gb Symbol Complete

:|magik-menu-heading|                  :en_gb Heading
:|magik-menu-comment|                  :en_gb Comment Region
:|magik-menu-uncomment|                :en_gb Uncomment Region
:|magik-menu-fill|                     :en_gb Fill Comment

:|magik-menu-toggle|                   :en_gb Toggle...
:|magik-menu-toggle-name-mode|         :en_gb Method Name Display
:|magik-menu-toggle-electric-mode|     :en_gb Electric Magik Mode
:|magik-menu-toggle-debug|             :en_gb Enable #Debug Statements
:|magik-menu-toggle-mark-exchange|     :en_gb Point at End of Marked Region
:|magik-menu-options|                  :en_gb Options:
:|magik-menu-option-eom-mode-on|       :en_gb Transmit Method = Move to End
:|magik-menu-option-eom-mode-off|      :en_gb Transmit Method = Do Not Move Point
:|magik-menu-option-eom-mode-repeat|   :en_gb Transmit Method = On Repeat, Move to End

:|magik-menu-language-help|            :en_gb Help: Magik Language Reference

:|magik-imenu-package|                 :en_gb Package
:|magik-imenu-globals|                 :en_gb Globals
:|magik-imenu-exemplars|               :en_gb Exemplars
:|magik-imenu-arrays|                  :en_gb Arrays
:|magik-imenu-binary-operator|         :en_gb Operators
:|magik-imenu-mixins|                  :en_gb Mixins
:|magik-imenu-pseudo-slots|            :en_gb Pseudo Slots
:|magik-imenu-slot-access|             :en_gb Slot Access
:|magik-imenu-shared-constants|        :en_gb Shared Constants
:|magik-imenu-shared-variables|        :en_gb Shared Variables
:|magik-imenu-property|                :en_gb Properties
:|magik-imenu-conditions|              :en_gb Conditions
:|magik-imenu-procedures|              :en_gb Procedures
:|magik-imenu-new|                     :en_gb new/init
:|magik-imenu-display|                 :en_gb show/write/print/trace
:|magik-imenu-abstract|                :en_gb Abstract
:|magik-imenu-private|                 :en_gb Private
:|magik-imenu-iterators|               :en_gb Iterators
:|magik-imenu-methods|                 :en_gb Public Methods

:|magik-electric-template-prompt|            :en_gb Electric template:
:|magik-goto-method-prompt|                  :en_gb Method Name
:|magik-goto-class-prompt|                   :en_gb Class Name
:|magik-goto-class-method-loop-start-prompt| :en_gb Warning: Goto first definition of '#1'
:|magik-goto-class-method-loop-prompt|       :en_gb Warning: Goto next definition of '#1'

:|magik-electric-on|                   :en_gb Electric Magik on.
:|magik-electric-off|                  :en_gb Electric Magik off.
:|magik-method-name-on|                :en_gb Method name display on.
:|magik-method-name-off|               :en_gb Method name display off.
:|transmit-magik-debug-on|             :en_gb Magik DEBUG statements on
:|transmit-magik-debug-off|            :en_gb Magik DEBUG statements off
:|magik-mark-method-exchange-on|       :en_gb Cursor will be placed at end of marked region.
:|magik-mark-method-exchange-off|      :en_gb Cursor will be placed at start of marked region.
:|magik-transmit-method-eom-on|        :en_gb After transmit method cursor will move to end of method
:|magik-transmit-method-eom-off|       :en_gb After transmit method the cursor position will be unaffected
:|magik-transmit-method-eom-on-repeat| :en_gb After transmit method, cursor will move to end of method when command is repeated.

:|magik-transmit-string|               :en_gb Transmitting to #1
:|magik-code-loaded|                   :en_gb Code loaded from #1
:|magik-complete-empty-string|         :en_gb Doing a completion on the empty string would take too long
:|magik-complete-string|               :en_gb Symbol is already complete or is too short.

:|magik-mode-is-gis-error|             :en_gb Your gis buffer has got into magik mode!  To recover, type `M-x gis-mode'.  Please report this bug.
:|magik-expecting-token-error|         :en_gb Found '#1' when expecting '#2'
:|magik-transmit-error|                :en_gb Don't know what to transmit
:|magik-no-round-bracket-error|        :en_gb Can't find closing round ) bracket
:|magik-no-square-bracket-error|       :en_gb Can't find closing square ] bracket
:|magik-unquoted-multibyte-error|      :en_gb Found unquoted multibyte character at position #1
:|magik-electric-no-template-error|    :en_gb There is no template for #1
:|magik-no-current-variable-error|     :en_gb No current variable to print
:|magik-goto-no-m-error|               :en_gb Cannot find method '#1'
:|magik-goto-no-m-in-c-error|          :en_gb Cannot find method, '#1', in class, '#2'
