#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_menu_sw

:|menu-sw-dev|                :en_gb Dev
:|menu-sw-dev-get-bug|        :en_gb Get Bug Report
:|menu-sw-dev-make-patch|     :en_gb Get/make Patch
:|menu-sw-dev-make-cn|        :en_gb Make Change Note
:|menu-sw-dev-make-unit-test| :en_gb Make Unit Test
:|menu-sw-dev-submit|         :en_gb Submit Patch
:|menu-sw-dev-review|         :en_gb Review Patch
:|menu-sw-dev-query|          :en_gb Query Patch
:|menu-sw-dev-approve|        :en_gb Approve Patch
:|menu-sw-dev-unsubmit|       :en_gb Unsubmit Patch
:|menu-sw-dev-unreview|       :en_gb UnReview Patch
:|menu-sw-dev-reject|         :en_gb Reject Patch
:|menu-sw-dev-resurrect|      :en_gb Resurrect Patch
:|menu-sw-dev-help|           :en_gb Patch Help
