#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_module

:|module-menu|                        :en_gb Module
:|module-menu-load-module|            :en_gb Load Module
:|module-menu-reload-definition|      :en_gb Reload Module Definition
:|module-menu-compile-messages|       :en_gb Compile Module Messages
:|module-menu-remove-module|          :en_gb Remove Module
:|module-menu-set-options|            :en_gb Set Options...

:|module-menu-option-save-magikc-false|          :en_gb Set :save_magikc? to _false
:|module-menu-option-save-magikc-true|           :en_gb Set :save_magikc? to _true
:|module-menu-option-force-reload-false|         :en_gb Set :force_reload? to _false
:|module-menu-option-force-reload-prerequisites| :en_gb Set :force_reload? to :prerequisites
:|module-menu-option-force-reload-true|          :en_gb Set :force_reload? to _true

:|module-option-save-magikc-set|      :en_gb Set :save_magikc? to #1
:|module-option-force-reload-set|     :en_gb Set :force_reload? option to #1
