#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_msg

:|msg-menu|                     :en_gb Message
:|msg-menu-transmit-buffer|     :en_gb Transmit Buffer
:|msg-menu-compile-module|      :en_gb Compile Message File
:|msg-menu-mark-message|        :en_gb Mark Message
:|msg-menu-next|                :en_gb Next
:|msg-menu-previous|            :en_gb Previous

:|msg-loaded-in-buffer|         :en_gb #1 loaded in buffer #2.
:|msg-compile-module-in-buffer| :en_gb Compiling all module messages in #1. 
