#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_pragma

:|pragma-topic-select|                  :en_gb Topic Select

:|pragma-deprecated-template|           :en_gb Use toggle keys, \\ and /, on 'Action' line to choose action.

:|pragma-yn-deprecated-modify-comments| :en_gb Remove modifed deprecated comments?

:|pragma-no-smallworld-gis-env|         :en_gb There is no value for $SMALLWORLD_GIS
