#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
#Contains the more generic messages that are used.
+ emacs_sw

:|sw-find-tag-default-prompt|     :en_gb #1 (default #2)

:|sw-yn-buffer-modified|          :en_gb Buffer for filename #1 modified - save changes?
:|sw-yn-continue|                 :en_gb Continue?

:|sw-help-info|                   :en_gb Emacs help displayed using Info
:|sw-help-htmlhelp|               :en_gb Emacs help displayed using HTML Help
:|sw-help-no-htmlhelp-file-error| :en_gb Failed to locate HTML Help file '#1'

:|sw-buffer-modified-error|       :en_gb Abandoned!
:|sw-no-gis-process-error|        :en_gb There is no GIS process running in buffer '#1'
:|sw-view-load-path-file-error|   :en_gb Impossible Error! Cannot find '#1' in 'load-path'
:|sw-no-directory-error|          :en_gb Directory does not exist: #1
:|sw-no-process-error|            :en_gb The '#1' buffer has no process running

