#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_aliases

:|aliases-menu|              :en_gb Aliases
:|aliases-menu-run-gis|      :en_gb Run Current Definition
:|aliases-menu-definitions|  :en_gb Definitions
:|aliases-menu-none-found|   :en_gb No Aliases found
:|aliases-sw-menu-rescan|    :en_gb *Rescan*

:|aliases-definition-prompt| :en_gb Definition:
:|aliases-cwd-prompt|        :en_gb Set current working directory:

:|aliases-command|           :en_gb Command
:|aliases-cwd|               :en_gb Cwd is: #1

:|aliases-no-definition|     :en_gb Cannot find any alias definitions


