#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_gis_version

:|g-v-menu|                    :en_gb Environment
:|g-v-menu-select|             :en_gb Select
:|g-v-menu-run|                :en_gb Run Gis Command
:|g-v-menu-next|               :en_gb Next Environment
:|g-v-menu-aliases|            :en_gb Open Aliases File
:|g-v-menu-quit|               :en_gb Quit
:|g-v-menu-file-add|           :en_gb Add New Installation
:|g-v-menu-reset|              :en_gb Reset Process Environment

:|g-v-yn-file-create|          :en_gb Create File Interface for SW Environments?
:|g-v-yn-reset|                :en_gb Are you sure you want to reset the process environment?

:|g-v-file-prompt|             :en_gb Enter New Environment List File:
:|g-v-smallworld-gis-prompt|   :en_gb Enter product directory for Core installation:
:|g-v-name-prompt|             :en_gb Enter name for this installation:
:|g-v-version-prompt|          :en_gb Enter version number of this installation:
:|g-v-lp-alias-prompt|         :en_gb Select a Layered Product with gis_aliases file:

:|g-v-starting-command|        :en_gb Starting #1 selection...
:|g-v-starting-command-done|   :en_gb Starting #1 selection... done
:|g-v-current|                 :en_gb The current installation for this Emacs is now #1.
:|g-v-current-version|         :en_gb Gis Environment: #1
:|g-v-invalid-warning-1|       :en_gb ** Can't find the currently selected product, #1.
:|g-v-invalid-warning-2|       :en_gb ** (Attempting to run anyway).

:|g-v-no-command-error|        :en_gb Cannot find the #1 command
:|g-v-position-error|          :en_gb No Environment at this point
:|g-v-invalid-error|           :en_gb You have selected an (invalid) Environment
:|g-v-match-error|             :en_gb No Environment on this line
:|g-v-invalid-selection-error| :en_gb Invalid selection
:|g-v-file-not-used-error|     :en_gb File interface is not being used
