#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_menu_sw

:|menu-sw|                      :en_gb SW
:|menu-sw-gis-select|           :en_gb Select Smallworld Environment
:|menu-sw-run-gis|              :en_gb Run/Goto Smallworld Session
:|menu-sw-run-new-gis|          :en_gb Start New Smallworld Session
:|menu-sw-alias-files|          :en_gb Alias Files
:|menu-sw-gis-procs|            :en_gb Gis Processes
:|menu-sw-cb-procs|             :en_gb Class Browser Processes
:|menu-sw-shell-procs|          :en_gb Shell Processes
:|menu-sw-list-procs|           :en_gb List Processes
:|menu-sw-no-procs|             :en_gb No Processes
:|menu-sw-tools|                :en_gb Tools
:|menu-sw-help|                 :en_gb Help
:|menu-sw-customize|            :en_gb Customise
:|menu-sw-customize-smallworld| :en_gb Customise Smallworld Emacs

:|menu-sw-help-info|            :en_gb Help using Info
:|menu-sw-help-htmlhelp|        :en_gb Help using HTMLHelp
:|menu-sw-help-sw-menu|         :en_gb SW Menu Help
:|menu-sw-help-keys|            :en_gb Smallworld Emacs Keys
:|menu-sw-help-toggle|          :en_gb Prefer HTML Help
:|menu-sw-help-view-file|       :en_gb View #1
