#% text_encoding = iso8859_1
### Internationalisation of Smallworld Emacs.
+ emacs_mpde

:|mpde-menu|                              :en_gb MPDE
:|mpde-menu-set|                          :en_gb Set Configuration
:|mpde-menu-refresh|                      :en_gb Refresh
:|mpde-menu-upload-submissions|           :en_gb Upload Submissions
:|mpde-menu-available|                    :en_gb Available Configurations
:|mpde-menu-display-configuration|        :en_gb Display Configuration
:|mpde-menu-display-resource|             :en_gb Display Resource
:|mpde-menu-make|                         :en_gb Make Configuration
:|mpde-menu-delete|                       :en_gb Delete Configuration
:|mpde-menu-install|                      :en_gb Install MPDE in .emacs
:|mpde-menu-dired-upload|                 :en_gb SW Upload...
:|mpde-menu-dired-upload-help|            :en_gb SW Upload current file or all marked files

:|mpde-available-configurations|          :en_gb Magik Patch Development Environment Configurations
:|mpde-loading-configuration|             :en_gb MPDE: Loading configuration settings for #1
:|mpde-refreshing-configuration|          :en_gb Refreshing Configuration: #1...
:|mpde-upload-submissions|                :en_gb Mark the files to upload then press the U key.

:|mpde-refreshing-directories|            :en_gb directories
:|mpde-refreshing-files|                  :en_gb files
:|mpde-refreshing-data|                   :en_gb data
:|mpde-refreshing-boot|                   :en_gb boot
:|mpde-refreshing-done|                   :en_gb done
:|mpde-refreshing-failed|                 :en_gb done with error
:|mpde-yn-refresh|                        :en_gb Refresh #1 configuration from master?
:|mpde-yn-reload-elisp|                   :en_gb Load the refreshed Smallworld Lisp code in this session?
:|mpde-yn-overwrite-dotmpde|              :en_gb File exists ~/.mpde. Overwrite and loose all configuration definitions?
:|mpde-yn-install-mpde|                   :en_gb Your .emacs file already includes MPDE configuration data. Continue?
:|mpde-yn-create-root-directory|          :en_gb The root directory #1 does not exist, create it now?
:|mpde-yn-delete-configuration|           :en_gb Deleting #1. Are you sure?
:|mpde-source-dir|                        :en_gb source     :
:|mpde-destination-dir|                   :en_gb destination:
:|mpde-copied-file-to|                    :en_gb Copied file #1 to #2...
:|mpde-copied-files|                      :en_gb Copied files in directory #1 to #2...
:|mpde-copied-files-matching|             :en_gb Copied files in directory #1 matching #2 to #3...
:|mpde-creating-file|                     :en_gb Creating file #1
:|mpde-storing-file|                      :en_gb Storing file #1
:|mpde-created-directory|                 :en_gb Created directory #1
:|mpde-copying-directory-to|              :en_gb Copied directory #1 to #2...
:|mpde-copying-files|                     :en_gb Copying files in directory #1 to #2...
:|mpde-copying-files-matching|            :en_gb Copying files in directory #1 matching #2 to #3...
:|mpde-configuration-prompt|              :en_gb Configuration name:
:|mpde-configuration-default|             :en_gb local
:|mpde-configuration-description-prompt|  :en_gb Description:
:|mpde-configuration-description-default| :en_gb My #1 setup
:|mpde-configuration-root-dir|            :en_gb #1 root directory:
:|mpde-resource-variables|                :en_gb Resource variables
:|mpde-resource-variable|                 :en_gb Resource variable
:|mpde-resource-deprecated|               :en_gb (DEPRECATED)
:|mpde-resource-documentation|            :en_gb Documentation:
:|mpde-resource-action|                   :en_gb ACTION:
:|mpde-resource-current-value|            :en_gb Current value is =
:|mpde-resource-no-docstring|             :en_gb No documentation available.
:|mpde-action-void-variable|              :en_gb MPDE: Void variable #1, ignoring...
:|mpde-action-no-action|                  :en_gb MPDE: No action defined for variable #1
:|mpde-debug|                             :en_gb DEBUG:
:|mpde-removed-entry|                     :en_gb MPDE: removed #1 entry from ~/.mpde
:|mpde-refresh-master-error|              :en_gb Cannot refresh the master configuration!
:|mpde-save-overwrite-error|              :en_gb Saving settings from 'emacs -q' would overwrite existing customizations
:|mpde-copy-dir-error|                    :en_gb Directory copy failed with exit status: #1
:|mpde-delete-dir-error|                  :en_gb Deletion of #1 failed with exit status: #2
:|mpde-configuration-unknown-error|       :en_gb Configuration #1 is not defined
:|mpde-no-master-error|                   :en_gb Master configuration is not accessible
:|mpde-no-master-template-error|          :en_gb Master template file #1 does not exist
:|mpde-no-boot-library-error|             :en_gb Master boot library #1 does not exist
:|mpde-already-installed-error|           :en_gb Aborted since your .emacs file includes MPDE configuration data
:|mpde-not-master-error|                  :en_gb Current configuration is not Master
:|mpde-no-parent-directory-error|         :en_gb Current configuration is not Master
:|mpde-delete-master-error|               :en_gb You cannot delete the master configuration!
:|mpde-delete-current-error|              :en_gb You cannot delete the current configuration: #1!
:|mpde-delete-abort-error|                :en_gb Deletion of #1 aborted
:|mpde-failed-validation-error|           :en_gb Cannot complete '#1' action. Offline configuration is #2
:|mpde-loosing-changes-error|             :en_gb MPDE: Cannot save buffer without loosing changes at refresh
:|mpde-file-exists-error|                 :en_gb File exists #1
